export const members = [
  {
    id: 'member-1',
    name: 'Richard Enrico',
    position: 'Front End Developer',
    gender: 'Laki-laki',
    phoneNumber: '+6281342777462',
    birthDate: new Date(),
  },
  {
    id: 'member-2',
    name: 'Muhammad Ikhsan',
    position: 'Mobile Developer',
    gender: 'Laki-laki',
    phoneNumber: '+6282342777462',
    birthDate: new Date(),
    imageUrl: '@/assets/images/member-2.png',
  },
  {
    id: 'member-3',
    name: 'Bayu Ajid',
    position: 'UI/UX Designer',
    gender: 'Laki-laki',
    phoneNumber: '+6283342777462',
    birthDate: new Date(),
    imageUrl: '@/assets/images/member-3.png',
  },
  {
    id: 'member-4',
    name: 'Silverius Sony',
    position: 'Front End Developer',
    gender: 'Laki-laki',
    phoneNumber: '+6284342777462',
    birthDate: new Date(),
    imageUrl: '@/assets/images/member-4.png',
  },
];
